channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.0
- pip:
  - mlflow==2.14.3
  - category-encoders==2.6.3
  - cffi==1.16.0
  - cloudpickle==3.0.0
  - graphviz==0.20.3
  - imbalanced-learn==0.12.3
  - lightgbm==4.4.0
  - matplotlib==3.9.1
  - mlxtend==0.23.1
  - numpy==1.26.4
  - packaging==24.1
  - pandas==2.2.2
  - psutil==6.0.0
  - pyarrow==15.0.2
  - scikit-learn==1.5.1
  - scipy==1.14.0
  - seaborn==0.13.2
  - xgboost==2.1.0
name: mlflow-env
